# Generated by Django 5.2.7 on 2025-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('birth', models.CharField(blank=True, max_length=120)),
                ('death', models.CharField(blank=True, max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='biographies/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
